[features]
seeds = false
skip-lint = false

[programs.localnet]
chain_guess = "6ApCN7LLT3Zmq898SML76PG3RkVnTDVasAFxsiwmbeFT"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
client = "yarn run ts-node client/*.ts"
